const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<dialog id="companion-dialog"><div class="companion-grid"></div></dialog>',{runScripts:'outside-only',url:'http://localhost/'}),w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
w.confirm=()=>true;
let stored=[{name:'Battery',enabled:true,elements:[{kind:'text',x:0,y:0,w:96,h:8,size:1,text:'Original'}]}],calls=[];
w.fetch=async(url,opts)=>{
 const body=opts.body?JSON.parse(opts.body):null;calls.push(body);
 if(body?.action==='save')stored=body.pages;
 return {ok:true,json:async()=>({ok:true,compatible:true,pages:structuredClone(stored),revision:'rev',values:{'battery.voltage':'Battery voltage'},series:{'battery.voltage':'Battery voltage'},drawing:{texts:[[0,0,1,'<test>']],lines:[]}})};
};
const tick=()=>new Promise(r=>setImmediate(r));
const button=t=>[...d.querySelectorAll('button')].find(b=>b.textContent===t);
(async()=>{
 w.eval(fs.readFileSync('meshcorestation/web/assets/oled_editor.js','utf8'));
 await tick();button('Open screen editor').click();await tick();await tick();
 assert(d.getElementById('oled-editor').open);
 assert(d.getElementById('oled-pixels').textContent.includes('<test>'));
 assert.equal(d.querySelectorAll('#oled-pixels test').length,0);
 button('+ Graph').click();
 const canvas=d.getElementById('oled-canvas');
 canvas.getBoundingClientRect=()=>({width:512,height:256});
 let box=d.querySelector('.oled-box.selected');
 box.dispatchEvent(new w.MouseEvent('pointerdown',{clientX:0,clientY:0,bubbles:true}));
 d.dispatchEvent(new w.MouseEvent('pointermove',{clientX:40,clientY:16,bubbles:true}));
 d.dispatchEvent(new w.MouseEvent('pointerup',{bubbles:true}));
 assert.equal(d.querySelector('[aria-label="X"]').value,'10');
 assert.equal(d.querySelector('[aria-label="Y"]').value,'20');
 d.querySelector('.oled-handle').dispatchEvent(new w.MouseEvent('pointerdown',{clientX:0,clientY:0,bubbles:true}));
 d.dispatchEvent(new w.MouseEvent('pointermove',{clientX:-40,clientY:-16,bubbles:true}));
 d.dispatchEvent(new w.MouseEvent('pointerup',{bubbles:true}));
 assert.equal(d.querySelector('[aria-label="Width"]').value,'90');
 const min=d.querySelector('[aria-label="Minimum"]');min.value='2.8';min.dispatchEvent(new w.Event('change'));
 assert.equal(calls.filter(c=>c?.action==='save').length,0);
 button('Save pages').click();await tick();
 assert.equal(stored[0].elements[1].minimum,2.8);
 assert.equal(stored[0].elements[1].w,90);
 button('Duplicate').click();await tick();
 assert.equal(d.querySelectorAll('#oled-pages button').length,2);
 button('Preview on companion (30s)').click();await tick();
 assert(calls.some(c=>c?.action==='device_preview'));
 d.getElementById('oled-close').click();await tick();
 assert(calls.some(c=>c?.action==='stop_preview'));
 assert(!d.getElementById('oled-editor').open);
 dom.window.close();console.log('OLED drag, resize, graph bounds, save, duplicate, safe text and preview checks passed.');
})().catch(e=>{console.error(e);dom.window.close();process.exit(1);});
